### ISSUE TITLE
rename bridgescorer-server-assembly jar file

### ISSUE THREAD

**Issue by thebridsk** [thebridsk/bridgescorer#281]
This requires the following steps:

new name `bridgescorekeeper-version-sha256`

- [x] change the update script to allow either the old name or the new name for the jar file
- [x] release it
- [x] get everyone to upgrade to this version
- [x] change name of jar file to new name
